[build]
  command = "npm run build"
  publish = "dist"  # or the specific directory where your build artifacts are generated
  base = "client"  # Set the base directory for the build process

[build.environment]
  NODE_ENV = "production"
